"""
Loader for settings.yaml - the one hand-edited settings file for the RGB/IR
sync POC (camera params, calibration/test tuning). See settings.yaml itself
for what each field means and why it's tunable.

Kept separate from config.yaml on purpose: config.yaml is auto-generated by
led_calibration.py (rewritten wholesale on every run), so nothing hand-edited
should live there.
"""

import os
import yaml

SETTINGS_PATH = "settings.yaml"


def load_settings(path=SETTINGS_PATH):
    with open(path, "r") as f:
        return yaml.safe_load(f)


def ensure_output_dir(settings):
    """Create paths.output_dir if it doesn't exist yet, return its path."""
    output_dir = settings["paths"]["output_dir"]
    os.makedirs(output_dir, exist_ok=True)
    return output_dir
